### ISSUE TITLE
Biome tags

### ISSUE THREAD

**Issue by hipsterjazzbo** [lilypuree/Metabolism#3]
Hi! Firstly, I *love* this mod. It's what I've been looking for for a long time!

I just wanted to make a suggestion, which is to use the forge (`#forge:is_hot`) and/or minecraft (`#minecraft:is_hot`) biome tags, in addition to or instead of the mod-specific ones.

This gist has a bit more detail: https://gist.github.com/TelepathicGrunt/b768ce904baa4598b21c3ca42f137f23

**Comment by lilypuree** [comment]
I have a problem with the forge hot tags, they include too many biomes that I do not want to consider hot.

**Comment by lilypuree** [comment]
For example it contains the savanna or savanna plateau, or stony peaks. imo jungles or deserts or badlands offer something unique for the player compared to the 'normal' biomes like plains or forests, but savannahs are just recolored plains, at least in the current version of Minecraft. Making it hot there will just cause people to ignore the biome.

**Comment by hipsterjazzbo** [comment]
Yeah that's certainly true. 

What about using `forget:is_desert`? It'd be nice to use some of the standard ones, even optionally, so that this could work with biome mods.

**Comment by hipsterjazzbo** [comment]
Or, another random thought: accept biome tags as well as biome ids in the json

**Comment by lilypuree** [comment]
That last idea is hard because vanilla Minecraft doesn't support biome tags in their location predicates yet. But I could add a custom one that does.

**Comment by lilypuree** [comment]
Added in the latest update, through the advancedlocationcheck condition you can use biome tags
